/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as OfficesOfficeIdRouteImport } from './routes/offices.$officeId'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as BranchesBranchIdRouteImport } from './routes/branches.$branchId'
import { Route as AdvisorsAdvisorIdRouteImport } from './routes/advisors.$advisorId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesOfficeIdRoute = OfficesOfficeIdRouteImport.update({
  id: '/offices/$officeId',
  path: '/offices/$officeId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesBranchIdRoute = BranchesBranchIdRouteImport.update({
  id: '/branches/$branchId',
  path: '/branches/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsAdvisorIdRoute = AdvisorsAdvisorIdRouteImport.update({
  id: '/advisors/$advisorId',
  path: '/advisors/$advisorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/integrations': typeof IntegrationsRoute
  '/security': typeof SecurityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/advisors/$advisorId': typeof AdvisorsAdvisorIdRoute
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/offices/$officeId': typeof OfficesOfficeIdRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/integrations': typeof IntegrationsRoute
  '/security': typeof SecurityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/advisors/$advisorId': typeof AdvisorsAdvisorIdRoute
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/offices/$officeId': typeof OfficesOfficeIdRoute
  '/leads': typeof LeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/integrations': typeof IntegrationsRoute
  '/security': typeof SecurityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/advisors/$advisorId': typeof AdvisorsAdvisorIdRoute
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/offices/$officeId': typeof OfficesOfficeIdRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/integrations'
    | '/security'
    | '/dashboard'
    | '/advisors/$advisorId'
    | '/branches/$branchId'
    | '/leads/$leadId'
    | '/offices/$officeId'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/integrations'
    | '/security'
    | '/dashboard'
    | '/advisors/$advisorId'
    | '/branches/$branchId'
    | '/leads/$leadId'
    | '/offices/$officeId'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/integrations'
    | '/security'
    | '/_authenticated/dashboard'
    | '/advisors/$advisorId'
    | '/branches/$branchId'
    | '/leads/$leadId'
    | '/offices/$officeId'
    | '/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  IntegrationsRoute: typeof IntegrationsRoute
  SecurityRoute: typeof SecurityRoute
  AdvisorsAdvisorIdRoute: typeof AdvisorsAdvisorIdRoute
  BranchesBranchIdRoute: typeof BranchesBranchIdRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  OfficesOfficeIdRoute: typeof OfficesOfficeIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/$officeId': {
      id: '/offices/$officeId'
      path: '/offices/$officeId'
      fullPath: '/offices/$officeId'
      preLoaderRoute: typeof OfficesOfficeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$branchId': {
      id: '/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/branches/$branchId'
      preLoaderRoute: typeof BranchesBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors/$advisorId': {
      id: '/advisors/$advisorId'
      path: '/advisors/$advisorId'
      fullPath: '/advisors/$advisorId'
      preLoaderRoute: typeof AdvisorsAdvisorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  IntegrationsRoute: IntegrationsRoute,
  SecurityRoute: SecurityRoute,
  AdvisorsAdvisorIdRoute: AdvisorsAdvisorIdRoute,
  BranchesBranchIdRoute: BranchesBranchIdRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  OfficesOfficeIdRoute: OfficesOfficeIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
